spring.application.name=app
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/fashion_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
jwt.secret=dGhpc0lzQVZlcnlTZWNyZXRLZXlGb3JKd3RUb2tlblNpZ25pbmdJbk15RmFzaGlvblNob3BBcHA=
jwt.access-token-expiration=1800000
jwt.refresh-token-expiration=604800000